// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxUs93mPDENri0o6ARCDOm5p_m40D-y78',
    appId: '1:804926032268:web:6450c694a8bbc705982ea9',
    messagingSenderId: '804926032268',
    projectId: 'mybus-5a992',
    authDomain: 'mybus-5a992.firebaseapp.com',
    storageBucket: 'mybus-5a992.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxUs93mPDENri0o6ARCDOm5p_m40D-y78',
    appId: '1:804926032268:android:6450c694a8bbc705982ea9',
    messagingSenderId: '804926032268',
    projectId: 'mybus-5a992',
    storageBucket: 'mybus-5a992.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxUs93mPDENri0o6ARCDOm5p_m40D-y78',
    appId: '1:804926032268:ios:6450c694a8bbc705982ea9',
    messagingSenderId: '804926032268',
    projectId: 'mybus-5a992',
    storageBucket: 'mybus-5a992.firebasestorage.app',
    iosBundleId: 'com.example.mybus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxUs93mPDENri0o6ARCDOm5p_m40D-y78',
    appId: '1:804926032268:ios:6450c694a8bbc705982ea9',
    messagingSenderId: '804926032268',
    projectId: 'mybus-5a992',
    storageBucket: 'mybus-5a992.firebasestorage.app',
    iosBundleId: 'com.example.mybus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxUs93mPDENri0o6ARCDOm5p_m40D-y78',
    appId: '1:804926032268:web:6450c694a8bbc705982ea9',
    messagingSenderId: '804926032268',
    projectId: 'mybus-5a992',
    authDomain: 'mybus-5a992.firebaseapp.com',
    storageBucket: 'mybus-5a992.firebasestorage.app',
  );
}
